# Site settings

title: "Jasper's Portfolio"
title_separator: "|"
name: "Jasper E. Hunt"
email: "JasperEHunt@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Jasper E. Hunt is a data scientist who completed his PhD at the 
  University of Oxford. He has 8+ years of quantitative research
  and machine learning experience. This is his portfolio site.
url: "http://JasperEHunt.github.io"
baseurl: ""
repository: "JasperEHunt/JasperEHunt.github.io"
github_username:  "JasperEHunt"
minimal_mistakes_skin: "dark"
masthead_title: "Jasper E. Hunt"

defaults:
  values:
    read_time: true
    words_per_minute: 250
    comments: false
    author_profile: true

author:
  name    : "Jasper E. Hunt"
  avatar  : "/assets/images/StirlingCastle.jpg"
  bio     : "Data scientist with 8+ years of quantitative research experience."
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin-in"
      url: "https://www.linkedin.com/in/jasperehunt/"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/JasperEHunt"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=hVbH4RUAAAAJ"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:JasperEHunt@gmail.com"

google_site_verification: "HXQi-ub-Ve_upuGLof40eHmScAHrrRh8eD9gw-FFoog"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
